export const DEMO_COMPANY = {
  id: 'demo-company-001',
  name: 'Titan Locksmith Demo',
  phone: '(555) 800-1234',
  email: 'ops@titanlocksmith.com',
  website: 'https://titanlocksmith.com',
  address: '4521 Commerce Dr, Houston, TX 77002',
  timezone: 'America/Chicago',
}

export const DEMO_TECHNICIANS = [
  { id: 'tech-001', company_id: 'demo-company-001', name: 'Marcus Reed', phone: '(555) 201-0001', email: 'marcus@titanlocksmith.com', active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 'tech-002', company_id: 'demo-company-001', name: 'Elena Cruz', phone: '(555) 201-0002', email: 'elena@titanlocksmith.com', active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 'tech-003', company_id: 'demo-company-001', name: 'Andre Thompson', phone: '(555) 201-0003', email: 'andre@titanlocksmith.com', active: true, created_at: '2024-01-01T00:00:00Z' },
  { id: 'tech-004', company_id: 'demo-company-001', name: 'Victor Nguyen', phone: '(555) 201-0004', email: 'victor@titanlocksmith.com', active: true, created_at: '2024-01-01T00:00:00Z' },
]

export const DEMO_CUSTOMERS = [
  { id: 'cust-001', company_id: 'demo-company-001', name: 'Sarah Mitchell', phone: '(555) 300-1001', email: 'sarah.mitchell@email.com', address: '1204 Oak Lane, Houston, TX 77001', notes: '', tags: [], created_at: '2024-06-01T00:00:00Z' },
  { id: 'cust-002', company_id: 'demo-company-001', name: 'James Okafor', phone: '(555) 300-1002', email: 'james.okafor@email.com', address: '8820 Westheimer Rd, Houston, TX 77063', notes: '', tags: [], created_at: '2024-06-01T00:00:00Z' },
  { id: 'cust-003', company_id: 'demo-company-001', name: 'Priya Sharma', phone: '(555) 300-1003', email: 'priya.sharma@email.com', address: '3301 Kirby Dr, Houston, TX 77098', notes: '', tags: [], created_at: '2024-06-01T00:00:00Z' },
  { id: 'cust-004', company_id: 'demo-company-001', name: 'David Hernandez', phone: '(555) 300-1004', email: 'david.h@email.com', address: '5502 Main St, Houston, TX 77002', notes: '', tags: [], created_at: '2024-06-02T00:00:00Z' },
  { id: 'cust-005', company_id: 'demo-company-001', name: 'Lisa Nguyen', phone: '(555) 300-1005', email: 'lisa.nguyen@email.com', address: '714 Heights Blvd, Houston, TX 77007', notes: '', tags: [], created_at: '2024-06-02T00:00:00Z' },
  { id: 'cust-006', company_id: 'demo-company-001', name: 'Robert Chen', phone: '(555) 300-1006', email: 'r.chen@email.com', address: '2200 Montrose Blvd, Houston, TX 77006', notes: '', tags: [], created_at: '2024-06-03T00:00:00Z' },
  { id: 'cust-007', company_id: 'demo-company-001', name: 'Angela Williams', phone: '(555) 300-1007', email: 'angela.w@email.com', address: '9900 Bellaire Blvd, Bellaire, TX 77401', notes: '', tags: [], created_at: '2024-06-03T00:00:00Z' },
  { id: 'cust-008', company_id: 'demo-company-001', name: 'Kevin Patel', phone: '(555) 300-1008', email: 'kpatel@email.com', address: '330 W Alabama St, Houston, TX 77006', notes: 'Commercial client', tags: ['commercial'], created_at: '2024-06-04T00:00:00Z' },
  { id: 'cust-009', company_id: 'demo-company-001', name: 'Monica Torres', phone: '(555) 300-1009', email: 'monica.t@email.com', address: '6400 Richmond Ave, Houston, TX 77057', notes: '', tags: [], created_at: '2024-06-04T00:00:00Z' },
  { id: 'cust-010', company_id: 'demo-company-001', name: 'Brian Jackson', phone: '(555) 300-1010', email: 'bjackson@email.com', address: '1100 Louisiana St, Houston, TX 77002', notes: '', tags: [], created_at: '2024-06-05T00:00:00Z' },
  { id: 'cust-011', company_id: 'demo-company-001', name: 'Rachel Kim', phone: '(555) 300-1011', email: 'rachel.kim@email.com', address: '4455 Shepherd Dr, Houston, TX 77019', notes: '', tags: [], created_at: '2024-06-05T00:00:00Z' },
  { id: 'cust-012', company_id: 'demo-company-001', name: 'Thomas Brown', phone: '(555) 300-1012', email: 'tbrown@email.com', address: '7801 Westpark Dr, Houston, TX 77063', notes: '', tags: [], created_at: '2024-06-06T00:00:00Z' },
  { id: 'cust-013', company_id: 'demo-company-001', name: 'Natasha Foster', phone: '(555) 300-1013', email: 'nfoster@email.com', address: '2910 Buffalo Speedway, Houston, TX 77098', notes: '', tags: [], created_at: '2024-06-06T00:00:00Z' },
  { id: 'cust-014', company_id: 'demo-company-001', name: 'Carlos Rivera', phone: '(555) 300-1014', email: 'c.rivera@email.com', address: '500 Crawford St, Houston, TX 77002', notes: '', tags: [], created_at: '2024-06-07T00:00:00Z' },
  { id: 'cust-015', company_id: 'demo-company-001', name: 'Jennifer Walsh', phone: '(555) 300-1015', email: 'j.walsh@email.com', address: '3800 Greenbriar Dr, Houston, TX 77098', notes: '', tags: [], created_at: '2024-06-07T00:00:00Z' },
]

function daysAgo(days: number, hour = 9, minute = 0): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

function today(hour: number, minute = 0): string {
  const d = new Date()
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

function daysFromNow(days: number, hour = 9, minute = 0): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

const now = new Date().toISOString()

export const DEMO_JOBS = [
  {
    id: 'job-001', company_id: 'demo-company-001', customer_id: 'cust-001', technician_id: 'tech-001',
    service_type: 'House Lockout', source: 'Phone', status: 'Completed' as const,
    address: '1204 Oak Lane, Houston, TX 77001',
    scheduled_start: daysAgo(28, 9), estimated_price: 95, final_price: 95,
    amount_collected: 95, payment_method: 'Cash' as const, payment_status: 'Cash Pending Verification' as const,
    cash_verification_status: 'pending' as const, payment_link_sent: false,
    parts_cost: 0, technician_notes: 'Standard house lockout, no damage to lock.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(28, 8), updated_at: daysAgo(28, 10),
  },
  {
    id: 'job-002', company_id: 'demo-company-001', customer_id: 'cust-002', technician_id: 'tech-002',
    service_type: 'Car Lockout', source: 'Google Business Profile', status: 'Completed' as const,
    address: '8820 Westheimer Rd, Houston, TX 77063',
    scheduled_start: daysAgo(27, 11), estimated_price: 75, final_price: 85,
    amount_collected: 85, payment_method: 'Payment Link' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/abc123',
    parts_cost: 0, technician_notes: 'Slim jim method worked.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(27, 8), updated_at: daysAgo(27, 12),
  },
  {
    id: 'job-003', company_id: 'demo-company-001', customer_id: 'cust-003', technician_id: 'tech-001',
    service_type: 'Rekey', source: 'Referral', status: 'Completed' as const,
    address: '3301 Kirby Dr, Houston, TX 77098',
    scheduled_start: daysAgo(26, 10), estimated_price: 150, final_price: 175,
    amount_collected: 175, payment_method: 'Card' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 25, technician_notes: 'Rekeyed 3 locks, front door, back door, garage.', notes: 'New homeowner.',
    created_by: 'dispatcher', created_at: daysAgo(26, 8), updated_at: daysAgo(26, 12),
  },
  {
    id: 'job-004', company_id: 'demo-company-001', customer_id: 'cust-004', technician_id: 'tech-003',
    service_type: 'Lock Replacement', source: 'Website', status: 'Completed' as const,
    address: '5502 Main St, Houston, TX 77002',
    scheduled_start: daysAgo(25, 14), estimated_price: 200, final_price: 245,
    amount_collected: 245, payment_method: 'Zelle' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/def456',
    parts_cost: 75, technician_notes: 'Replaced deadbolt and knob set.', notes: '',
    created_by: 'admin', created_at: daysAgo(25, 8), updated_at: daysAgo(25, 16),
  },
  {
    id: 'job-005', company_id: 'demo-company-001', customer_id: 'cust-005', technician_id: 'tech-004',
    service_type: 'Smart Lock Install', source: 'Google Business Profile', status: 'Completed' as const,
    address: '714 Heights Blvd, Houston, TX 77007',
    scheduled_start: daysAgo(24, 13), estimated_price: 350, final_price: 385,
    amount_collected: 385, payment_method: 'Card' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 120, technician_notes: 'Schlage Encode installed. Customer walked through app setup.', notes: 'Customer had the lock already, we installed only.',
    created_by: 'dispatcher', created_at: daysAgo(24, 8), updated_at: daysAgo(24, 15),
  },
  {
    id: 'job-006', company_id: 'demo-company-001', customer_id: 'cust-006', technician_id: 'tech-002',
    service_type: 'Safe Opening', source: 'Phone', status: 'Completed' as const,
    address: '2200 Montrose Blvd, Houston, TX 77006',
    scheduled_start: daysAgo(23, 15), estimated_price: 300, final_price: 350,
    amount_collected: 350, payment_method: 'Cash' as const, payment_status: 'Cash Pending Verification' as const,
    cash_verification_status: 'pending' as const, payment_link_sent: false,
    parts_cost: 0, technician_notes: 'Combination safe, manipulation method used.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(23, 8), updated_at: daysAgo(23, 17),
  },
  {
    id: 'job-007', company_id: 'demo-company-001', customer_id: 'cust-007', technician_id: 'tech-001',
    service_type: 'Emergency Locksmith', source: 'Phone', status: 'Completed' as const,
    address: '9900 Bellaire Blvd, Bellaire, TX 77401',
    scheduled_start: daysAgo(22, 23), estimated_price: 125, final_price: 150,
    amount_collected: 150, payment_method: 'Payment Link' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/ghi789',
    parts_cost: 10, technician_notes: 'Emergency call 11pm. Lock was damaged.', notes: 'After hours rate applied.',
    created_by: 'dispatcher', created_at: daysAgo(22, 22), updated_at: daysAgo(22, 23, 30),
  },
  {
    id: 'job-008', company_id: 'demo-company-001', customer_id: 'cust-008', technician_id: 'tech-003',
    service_type: 'Commercial Lock Repair', source: 'Referral', status: 'Completed' as const,
    address: '330 W Alabama St, Houston, TX 77006',
    scheduled_start: daysAgo(21, 9), estimated_price: 275, final_price: 310,
    amount_collected: 310, payment_method: 'Check' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 85, technician_notes: 'Commercial door closer and panic bar repaired.', notes: 'Net-30 terms discussed.',
    created_by: 'admin', created_at: daysAgo(21, 8), updated_at: daysAgo(21, 12),
  },
  {
    id: 'job-009', company_id: 'demo-company-001', customer_id: 'cust-009', technician_id: 'tech-004',
    service_type: 'Key Duplication', source: 'Phone', status: 'Completed' as const,
    address: '6400 Richmond Ave, Houston, TX 77057',
    scheduled_start: daysAgo(20, 11), estimated_price: 35, final_price: 45,
    amount_collected: 45, payment_method: 'Cash' as const, payment_status: 'Cash Pending Verification' as const,
    cash_verification_status: 'pending' as const, payment_link_sent: false,
    parts_cost: 8, technician_notes: '3 keys duplicated.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(20, 8), updated_at: daysAgo(20, 12),
  },
  {
    id: 'job-010', company_id: 'demo-company-001', customer_id: 'cust-010', technician_id: 'tech-002',
    service_type: 'Ignition Repair', source: 'Google Business Profile', status: 'Completed' as const,
    address: '1100 Louisiana St, Houston, TX 77002',
    scheduled_start: daysAgo(19, 10), estimated_price: 200, final_price: 225,
    amount_collected: 225, payment_method: 'Card' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/jkl012',
    parts_cost: 45, technician_notes: 'Ignition cylinder replaced.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(19, 8), updated_at: daysAgo(19, 12),
  },
  {
    id: 'job-011', company_id: 'demo-company-001', customer_id: 'cust-011', technician_id: 'tech-001',
    service_type: 'House Lockout', source: 'Phone', status: 'Completed' as const,
    address: '4455 Shepherd Dr, Houston, TX 77019',
    scheduled_start: daysAgo(18, 14), estimated_price: 95, final_price: 95,
    amount_collected: 95, payment_method: 'Venmo' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 0, technician_notes: 'Pick open. No damage.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(18, 8), updated_at: daysAgo(18, 15),
  },
  {
    id: 'job-012', company_id: 'demo-company-001', customer_id: 'cust-012', technician_id: 'tech-003',
    service_type: 'Lock Replacement', source: 'Yelp', status: 'Completed' as const,
    address: '7801 Westpark Dr, Houston, TX 77063',
    scheduled_start: daysAgo(17, 9), estimated_price: 220, final_price: 260,
    amount_collected: 260, payment_method: 'Card' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/mno345',
    parts_cost: 80, technician_notes: 'Replaced front and side door locks.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(17, 8), updated_at: daysAgo(17, 11),
  },
  {
    id: 'job-013', company_id: 'demo-company-001', customer_id: 'cust-013', technician_id: 'tech-004',
    service_type: 'Rekey', source: 'Website', status: 'Completed' as const,
    address: '2910 Buffalo Speedway, Houston, TX 77098',
    scheduled_start: daysAgo(16, 10), estimated_price: 120, final_price: 120,
    amount_collected: 120, payment_method: 'Payment Link' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/pqr678',
    parts_cost: 15, technician_notes: 'Rekeyed 2 locks.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(16, 8), updated_at: daysAgo(16, 12),
  },
  {
    id: 'job-014', company_id: 'demo-company-001', customer_id: 'cust-014', technician_id: 'tech-002',
    service_type: 'Car Lockout', source: 'Phone', status: 'Completed' as const,
    address: '500 Crawford St, Houston, TX 77002',
    scheduled_start: daysAgo(15, 16), estimated_price: 75, final_price: 75,
    amount_collected: 75, payment_method: 'Cash' as const, payment_status: 'Cash Pending Verification' as const,
    cash_verification_status: 'pending' as const, payment_link_sent: false,
    parts_cost: 0, technician_notes: 'Quick lockout, 15 min.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(15, 8), updated_at: daysAgo(15, 17),
  },
  {
    id: 'job-015', company_id: 'demo-company-001', customer_id: 'cust-015', technician_id: 'tech-001',
    service_type: 'Smart Lock Install', source: 'Google Business Profile', status: 'Completed' as const,
    address: '3800 Greenbriar Dr, Houston, TX 77098',
    scheduled_start: daysAgo(14, 13), estimated_price: 400, final_price: 450,
    amount_collected: 450, payment_method: 'Card' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/stu901',
    parts_cost: 150, technician_notes: 'August Smart Lock Pro + keypad installed.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(14, 8), updated_at: daysAgo(14, 15),
  },
  {
    id: 'job-016', company_id: 'demo-company-001', customer_id: 'cust-001', technician_id: 'tech-003',
    service_type: 'Emergency Locksmith', source: 'Phone', status: 'Completed' as const,
    address: '1204 Oak Lane, Houston, TX 77001',
    scheduled_start: daysAgo(13, 22), estimated_price: 150, final_price: 175,
    amount_collected: 175, payment_method: 'Cash' as const, payment_status: 'Cash Pending Verification' as const,
    cash_verification_status: 'pending' as const, payment_link_sent: false,
    parts_cost: 15, technician_notes: 'Broken key extraction. Lock still functional.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(13, 21), updated_at: daysAgo(13, 23),
  },
  {
    id: 'job-017', company_id: 'demo-company-001', customer_id: 'cust-002', technician_id: 'tech-004',
    service_type: 'Commercial Lock Repair', source: 'Referral', status: 'Completed' as const,
    address: '8820 Westheimer Rd, Houston, TX 77063',
    scheduled_start: daysAgo(12, 9), estimated_price: 350, final_price: 390,
    amount_collected: 390, payment_method: 'Check' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 110, technician_notes: 'Master key system installed for 5 doors.', notes: 'Commercial client — 2nd job this month.',
    created_by: 'admin', created_at: daysAgo(12, 8), updated_at: daysAgo(12, 14),
  },
  {
    id: 'job-018', company_id: 'demo-company-001', customer_id: 'cust-003', technician_id: 'tech-001',
    service_type: 'Safe Opening', source: 'Phone', status: 'Completed' as const,
    address: '3301 Kirby Dr, Houston, TX 77098',
    scheduled_start: daysAgo(11, 11), estimated_price: 275, final_price: 300,
    amount_collected: 300, payment_method: 'Zelle' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 0, technician_notes: 'Gun safe — electronic bypass used.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(11, 8), updated_at: daysAgo(11, 13),
  },
  {
    id: 'job-019', company_id: 'demo-company-001', customer_id: 'cust-004', technician_id: 'tech-002',
    service_type: 'House Lockout', source: 'Google Business Profile', status: 'Completed' as const,
    address: '5502 Main St, Houston, TX 77002',
    scheduled_start: daysAgo(10, 9), estimated_price: 95, final_price: 95,
    amount_collected: 0, payment_method: 'Payment Link' as const, payment_status: 'Payment Link Sent' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/vwx234',
    parts_cost: 0, technician_notes: 'Completed. Sent payment link.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(10, 8), updated_at: daysAgo(10, 11),
  },
  {
    id: 'job-020', company_id: 'demo-company-001', customer_id: 'cust-005', technician_id: 'tech-003',
    service_type: 'Ignition Repair', source: 'Phone', status: 'Completed' as const,
    address: '714 Heights Blvd, Houston, TX 77007',
    scheduled_start: daysAgo(9, 13), estimated_price: 185, final_price: 210,
    amount_collected: 210, payment_method: 'Card' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 50, technician_notes: 'Ignition switch replaced. Key programmed.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(9, 8), updated_at: daysAgo(9, 15),
  },
  {
    id: 'job-021', company_id: 'demo-company-001', customer_id: 'cust-006', technician_id: 'tech-004',
    service_type: 'Rekey', source: 'Website', status: 'Completed' as const,
    address: '2200 Montrose Blvd, Houston, TX 77006',
    scheduled_start: daysAgo(8, 10), estimated_price: 140, final_price: 160,
    amount_collected: 160, payment_method: 'Payment Link' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/yza567',
    parts_cost: 20, technician_notes: 'Rekeyed 4 locks.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(8, 8), updated_at: daysAgo(8, 12),
  },
  {
    id: 'job-022', company_id: 'demo-company-001', customer_id: 'cust-007', technician_id: 'tech-001',
    service_type: 'Key Duplication', source: 'Phone', status: 'Completed' as const,
    address: '9900 Bellaire Blvd, Bellaire, TX 77401',
    scheduled_start: daysAgo(7, 11), estimated_price: 25, final_price: 30,
    amount_collected: 30, payment_method: 'Cash' as const, payment_status: 'Cash Pending Verification' as const,
    cash_verification_status: 'pending' as const, payment_link_sent: false,
    parts_cost: 5, technician_notes: '2 house keys.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(7, 8), updated_at: daysAgo(7, 12),
  },
  {
    id: 'job-023', company_id: 'demo-company-001', customer_id: 'cust-008', technician_id: 'tech-002',
    service_type: 'Car Lockout', source: 'Google Business Profile', status: 'Completed' as const,
    address: '330 W Alabama St, Houston, TX 77006',
    scheduled_start: daysAgo(6, 15), estimated_price: 75, final_price: 85,
    amount_collected: 85, payment_method: 'Card' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/bcd890',
    parts_cost: 0, technician_notes: 'Tesla Model 3 lockout.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(6, 8), updated_at: daysAgo(6, 16),
  },
  {
    id: 'job-024', company_id: 'demo-company-001', customer_id: 'cust-009', technician_id: 'tech-003',
    service_type: 'Lock Replacement', source: 'Referral', status: 'Completed' as const,
    address: '6400 Richmond Ave, Houston, TX 77057',
    scheduled_start: daysAgo(5, 10), estimated_price: 230, final_price: 275,
    amount_collected: 275, payment_method: 'Zelle' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 90, technician_notes: 'Kwikset SmartKey set installed front and back.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(5, 8), updated_at: daysAgo(5, 12),
  },
  {
    id: 'job-025', company_id: 'demo-company-001', customer_id: 'cust-010', technician_id: 'tech-004',
    service_type: 'Emergency Locksmith', source: 'Phone', status: 'Completed' as const,
    address: '1100 Louisiana St, Houston, TX 77002',
    scheduled_start: daysAgo(4, 20), estimated_price: 200, final_price: 225,
    amount_collected: 225, payment_method: 'Cash' as const, payment_status: 'Cash Pending Verification' as const,
    cash_verification_status: 'pending' as const, payment_link_sent: false,
    parts_cost: 20, technician_notes: 'Business lockout — owner forgot keys.', notes: 'Emergency commercial rate.',
    created_by: 'dispatcher', created_at: daysAgo(4, 19), updated_at: daysAgo(4, 21),
  },
  {
    id: 'job-026', company_id: 'demo-company-001', customer_id: 'cust-011', technician_id: 'tech-001',
    service_type: 'Smart Lock Install', source: 'Google Business Profile', status: 'Assigned' as const,
    address: '4455 Shepherd Dr, Houston, TX 77019',
    scheduled_start: today(10), estimated_price: 350, final_price: null,
    amount_collected: 0, payment_method: null, payment_status: 'Unpaid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 0, technician_notes: '', notes: 'Customer has lock — install only.',
    created_by: 'dispatcher', created_at: daysAgo(1, 9), updated_at: daysAgo(1, 9),
  },
  {
    id: 'job-027', company_id: 'demo-company-001', customer_id: 'cust-012', technician_id: 'tech-002',
    service_type: 'Rekey', source: 'Phone', status: 'Scheduled' as const,
    address: '7801 Westpark Dr, Houston, TX 77063',
    scheduled_start: today(13, 30), estimated_price: 120, final_price: null,
    amount_collected: 0, payment_method: null, payment_status: 'Unpaid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 0, technician_notes: '', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(2, 9), updated_at: daysAgo(2, 9),
  },
  {
    id: 'job-028', company_id: 'demo-company-001', customer_id: 'cust-013', technician_id: 'tech-003',
    service_type: 'Car Lockout', source: 'Google Business Profile', status: 'En Route' as const,
    address: '2910 Buffalo Speedway, Houston, TX 77098',
    scheduled_start: today(9), estimated_price: 75, final_price: null,
    amount_collected: 0, payment_method: null, payment_status: 'Unpaid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/efg123',
    parts_cost: 0, technician_notes: '', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(1, 9), updated_at: now,
  },
  {
    id: 'job-029', company_id: 'demo-company-001', customer_id: 'cust-014', technician_id: 'tech-004',
    service_type: 'House Lockout', source: 'Phone', status: 'In Progress' as const,
    address: '500 Crawford St, Houston, TX 77002',
    scheduled_start: today(11), estimated_price: 95, final_price: null,
    amount_collected: 0, payment_method: null, payment_status: 'Unpaid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 0, technician_notes: '', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(1, 9), updated_at: now,
  },
  {
    id: 'job-030', company_id: 'demo-company-001', customer_id: 'cust-015', technician_id: null,
    service_type: 'Lock Replacement', source: 'Yelp', status: 'Scheduled' as const,
    address: '3800 Greenbriar Dr, Houston, TX 77098',
    scheduled_start: daysFromNow(1, 9), estimated_price: 240, final_price: null,
    amount_collected: 0, payment_method: null, payment_status: 'Unpaid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 0, technician_notes: '', notes: 'Prefers morning slot.',
    created_by: 'dispatcher', created_at: daysAgo(1, 9), updated_at: daysAgo(1, 9),
  },
  {
    id: 'job-031', company_id: 'demo-company-001', customer_id: 'cust-001', technician_id: 'tech-001',
    service_type: 'Commercial Lock Repair', source: 'Referral', status: 'Scheduled' as const,
    address: '1204 Oak Lane, Houston, TX 77001',
    scheduled_start: daysFromNow(2, 10), estimated_price: 300, final_price: null,
    amount_collected: 0, payment_method: null, payment_status: 'Unpaid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 0, technician_notes: '', notes: '',
    created_by: 'admin', created_at: daysAgo(1, 9), updated_at: daysAgo(1, 9),
  },
  {
    id: 'job-032', company_id: 'demo-company-001', customer_id: 'cust-003', technician_id: 'tech-002',
    service_type: 'Safe Opening', source: 'Phone', status: 'Cancelled' as const,
    address: '3301 Kirby Dr, Houston, TX 77098',
    scheduled_start: daysAgo(3, 14), estimated_price: 275, final_price: null,
    amount_collected: 0, payment_method: null, payment_status: 'Unpaid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 0, technician_notes: '', notes: 'Customer cancelled — rescheduling.',
    created_by: 'dispatcher', created_at: daysAgo(4, 9), updated_at: daysAgo(3, 8),
  },
  {
    id: 'job-033', company_id: 'demo-company-001', customer_id: 'cust-005', technician_id: 'tech-003',
    service_type: 'Key Duplication', source: 'Phone', status: 'Completed' as const,
    address: '714 Heights Blvd, Houston, TX 77007',
    scheduled_start: daysAgo(3, 11), estimated_price: 40, final_price: 40,
    amount_collected: 40, payment_method: 'Cash' as const, payment_status: 'Cash Pending Verification' as const,
    cash_verification_status: 'pending' as const, payment_link_sent: false,
    parts_cost: 8, technician_notes: '4 keys made.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(3, 8), updated_at: daysAgo(3, 12),
  },
  {
    id: 'job-034', company_id: 'demo-company-001', customer_id: 'cust-006', technician_id: 'tech-004',
    service_type: 'Ignition Repair', source: 'Google Business Profile', status: 'Completed' as const,
    address: '2200 Montrose Blvd, Houston, TX 77006',
    scheduled_start: daysAgo(2, 14), estimated_price: 195, final_price: 220,
    amount_collected: 220, payment_method: 'Card' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 55, technician_notes: 'Honda Civic ignition.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(2, 8), updated_at: daysAgo(2, 16),
  },
  {
    id: 'job-035', company_id: 'demo-company-001', customer_id: 'cust-007', technician_id: 'tech-001',
    service_type: 'House Lockout', source: 'Phone', status: 'No Show' as const,
    address: '9900 Bellaire Blvd, Bellaire, TX 77401',
    scheduled_start: daysAgo(2, 10), estimated_price: 95, final_price: null,
    amount_collected: 0, payment_method: null, payment_status: 'Unpaid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 0, technician_notes: 'No one home. Called twice.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(3, 9), updated_at: daysAgo(2, 11),
  },
  {
    id: 'job-036', company_id: 'demo-company-001', customer_id: 'cust-008', technician_id: 'tech-002',
    service_type: 'Smart Lock Install', source: 'Website', status: 'Completed' as const,
    address: '330 W Alabama St, Houston, TX 77006',
    scheduled_start: daysAgo(1, 9), estimated_price: 375, final_price: 395,
    amount_collected: 395, payment_method: 'Payment Link' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/hij456',
    parts_cost: 130, technician_notes: 'Yale Assure installed. Works great.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(2, 9), updated_at: daysAgo(1, 12),
  },
  {
    id: 'job-037', company_id: 'demo-company-001', customer_id: 'cust-009', technician_id: 'tech-003',
    service_type: 'Emergency Locksmith', source: 'Phone', status: 'Completed' as const,
    address: '6400 Richmond Ave, Houston, TX 77057',
    scheduled_start: daysAgo(1, 23), estimated_price: 175, final_price: 200,
    amount_collected: 200, payment_method: 'Cash' as const, payment_status: 'Cash Pending Verification' as const,
    cash_verification_status: 'pending' as const, payment_link_sent: false,
    parts_cost: 10, technician_notes: 'Midnight call. Forced entry damage — door knob replaced.', notes: 'Emergency premium applied.',
    created_by: 'dispatcher', created_at: daysAgo(1, 22), updated_at: daysAgo(1, 23, 30),
  },
  {
    id: 'job-038', company_id: 'demo-company-001', customer_id: 'cust-010', technician_id: 'tech-004',
    service_type: 'Rekey', source: 'Referral', status: 'Completed' as const,
    address: '1100 Louisiana St, Houston, TX 77002',
    scheduled_start: daysAgo(1, 13), estimated_price: 130, final_price: 155,
    amount_collected: 155, payment_method: 'Venmo' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 20, technician_notes: 'Move-out rekey 3 locks.', notes: '',
    created_by: 'dispatcher', created_at: daysAgo(2, 9), updated_at: daysAgo(1, 15),
  },
  {
    id: 'job-039', company_id: 'demo-company-001', customer_id: 'cust-011', technician_id: 'tech-001',
    service_type: 'Car Lockout', source: 'Google Business Profile', status: 'Completed' as const,
    address: '4455 Shepherd Dr, Houston, TX 77019',
    scheduled_start: today(8), estimated_price: 75, final_price: 75,
    amount_collected: 75, payment_method: 'Card' as const, payment_status: 'Paid' as const,
    cash_verification_status: null, payment_link_sent: true,
    payment_link_url: 'https://pay.titan.com/link/klm789',
    parts_cost: 0, technician_notes: 'F-150 lockout, slim jim.', notes: '',
    created_by: 'dispatcher', created_at: today(7), updated_at: today(8, 30),
  },
  {
    id: 'job-040', company_id: 'demo-company-001', customer_id: 'cust-012', technician_id: null,
    service_type: 'Lock Replacement', source: 'Phone', status: 'New Lead' as const,
    address: '7801 Westpark Dr, Houston, TX 77063',
    scheduled_start: daysFromNow(3, 10), estimated_price: 200, final_price: null,
    amount_collected: 0, payment_method: null, payment_status: 'Unpaid' as const,
    cash_verification_status: null, payment_link_sent: false,
    parts_cost: 0, technician_notes: '', notes: 'Called in this morning. Needs estimate.',
    created_by: 'dispatcher', created_at: today(9), updated_at: today(9),
  },
]

export const DEMO_EXPENSES = [
  { id: 'exp-001', company_id: 'demo-company-001', category: 'Payroll', amount: 12000, date: new Date().toISOString().split('T')[0], notes: 'Monthly technician payroll', recurring: true, created_at: now },
  { id: 'exp-002', company_id: 'demo-company-001', category: 'Vehicle', amount: 1800, date: new Date().toISOString().split('T')[0], notes: '4 trucks fuel + maintenance', recurring: true, created_at: now },
  { id: 'exp-003', company_id: 'demo-company-001', category: 'Insurance', amount: 850, date: new Date().toISOString().split('T')[0], notes: 'General liability + commercial auto', recurring: true, created_at: now },
  { id: 'exp-004', company_id: 'demo-company-001', category: 'Marketing', amount: 600, date: new Date().toISOString().split('T')[0], notes: 'Google Ads + Yelp', recurring: true, created_at: now },
  { id: 'exp-005', company_id: 'demo-company-001', category: 'Tools/Equipment', amount: 350, date: new Date().toISOString().split('T')[0], notes: 'Monthly supply restocking', recurring: true, created_at: now },
  { id: 'exp-006', company_id: 'demo-company-001', category: 'Misc', amount: 200, date: new Date().toISOString().split('T')[0], notes: 'Office + admin misc', recurring: false, created_at: now },
]
